# Generated by Django 4.2.1 on 2023-06-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_photo_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='user_pr',
            new_name='user_product',
        ),
        migrations.RenameField(
            model_name='usercart',
            old_name='user_pr_quan',
            new_name='user_product_quantity',
        ),
    ]
